
## command line input, you can change the input here to test further
## default is "Hello hi" with 0 a, 1 e, 1 i, 1 o, 0 u
hw4: 1_vowel_test.c 1_vowel.c 2_cotify.c
	gcc -o 1_vowel_test 1_vowel_test.c 1_vowel.c
	./1_vowel_test "Hello hi"
	gcc -o 2_cotify 2_cotify.c
	./2_cotify