pointer: 5_pointers.c
	gcc -o 5_pointers 5_pointers.c
	./5_pointers

hexa: 6_hexadecimal.c
	gcc -o 6_hexadecimal 6_hexadecimal.c
	./6_hexadecimal

foxish: 9_tests.c
	gcc -o 9_tests 9_tests.c
	./9_tests